spring:
    thread-executor: virtual
    application:
        name: registry

server:
    port: 8761

eureka:
    renewalPercentThreshold: 0.85
    instance:
        hostname: localhost
    client:
        fetch-registry: false
        register-with-eureka: false
